/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function generateMnemonic(): string
export declare function mnemonicToSeed(phrase: string, password?: string | undefined | null): Buffer
export declare function generateEd25519Keypair(): Array<Buffer>
export declare function generateX25519Keypair(): Array<Buffer>
export declare function ecdhSharedSecret(ourSecret: Uint8Array, theirPublic: Uint8Array): Buffer
export declare function signMessage(secretKey: Uint8Array, message: Uint8Array): Buffer
export declare function verifySignature(publicKey: Uint8Array, message: Uint8Array, signature: Uint8Array): boolean
export declare function encryptAesGcm(key: Uint8Array, plaintext: Uint8Array, aad?: Uint8Array | undefined | null): Buffer
export declare function decryptAesGcm(key: Uint8Array, ciphertext: Uint8Array, aad?: Uint8Array | undefined | null): Buffer
export declare function derivePbkdf2(password: Uint8Array, salt: Uint8Array, iterations: number, keyLen: number): Buffer
export declare function deriveHkdf(ikm: Uint8Array, salt: Uint8Array | undefined | null, info: Uint8Array | undefined | null, keyLen: number): Buffer
export declare function deriveSrk(dek: Uint8Array, chatId: Uint8Array): Buffer
export declare function deriveWindowKey(srk: Uint8Array, windowIndex: number): Buffer
export declare function wrapKey(kek: Uint8Array, keyToWrap: Uint8Array): Buffer
export declare function unwrapKey(kek: Uint8Array, wrappedKey: Uint8Array): Buffer
export declare function padMessage(content: Uint8Array): Buffer
export declare function packEnvelope(windowIndex: number, aadHash: Uint8Array, encryptedBlob: Uint8Array): Buffer
export interface UnpackedEnvelope {
  windowIndex: number
  aadHash: Buffer
  encryptedBlob: Buffer
}
export declare function unpackEnvelope(envelope: Uint8Array): UnpackedEnvelope
export declare function mlKemKeygen(): Array<Buffer>
export interface MlKemEncapsulationResult {
  ciphertext: Buffer
  sharedSecret: Buffer
}
export declare function mlKemEncapsulate(encapsulationKey: Uint8Array): MlKemEncapsulationResult
export declare function mlKemDecapsulate(decapsulationKey: Uint8Array, ciphertext: Uint8Array): Buffer
export interface HybridKemResult {
  sharedKey: Buffer
  mlKemCiphertext: Buffer
}
export declare function hybridKemEncapsulate(x25519OurSecret: Uint8Array, x25519TheirPublic: Uint8Array, mlKemEk: Uint8Array): HybridKemResult
export declare function hybridKemDecapsulate(x25519OurSecret: Uint8Array, x25519TheirPublic: Uint8Array, mlKemDk: Uint8Array, mlKemCt: Uint8Array): Buffer
export declare function authenticatedKemEncapsulate(ourX25519Sk: Uint8Array, recipientX25519Pub: Uint8Array, recipientMlkemEk: Uint8Array, senderIdentitySk: Uint8Array): Array<Buffer>
export declare function authenticatedKemDecapsulate(ourX25519Sk: Uint8Array, senderX25519Pub: Uint8Array, ourMlkemDk: Uint8Array, authenticatedCiphertext: Uint8Array, senderIdentityPk: Uint8Array): Buffer
export declare function registryEmpty(): string
export declare function registryAddDevice(registryJson: string, deviceId: string, name: string, addedAt: number, publicKey: string): string
export declare function registryRevokeDevice(registryJson: string, deviceId: string): string
export declare function registryGetActiveDevices(registryJson: string): string
export declare function generateRatchetKeypair(): Array<Buffer>
export declare function ratchetSrk(currentSrk: Uint8Array, ourRatchetSecret: Uint8Array, theirRatchetPub: Uint8Array, chatId: Uint8Array, ratchetStep: number, isSender: boolean): Buffer
export declare function shouldRatchet(messageCount: number, windowChanged: boolean, messagesPerRatchet: number, ratchetOnNewWindow: boolean): boolean
