/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function generateMnemonic(): string
export declare function mnemonicToSeed(phrase: string, password?: string | undefined | null): Buffer
export declare function generateEd25519Keypair(): Array<Buffer>
export declare function generateX25519Keypair(): Array<Buffer>
export declare function ecdhSharedSecret(ourSecret: Uint8Array, theirPublic: Uint8Array): Buffer
export declare function signMessage(secretKey: Uint8Array, message: Uint8Array): Buffer
export declare function verifySignature(publicKey: Uint8Array, message: Uint8Array, signature: Uint8Array): boolean
export declare function encryptAesGcm(key: Uint8Array, plaintext: Uint8Array, aad?: Uint8Array | undefined | null): Buffer
export declare function decryptAesGcm(key: Uint8Array, ciphertext: Uint8Array, aad?: Uint8Array | undefined | null): Buffer
export declare function derivePbkdf2(password: Uint8Array, salt: Uint8Array, iterations: number, keyLen: number): Buffer
export declare function deriveHkdf(ikm: Uint8Array, salt: Uint8Array | undefined | null, info: Uint8Array | undefined | null, keyLen: number): Buffer
export declare function deriveSrk(dek: Uint8Array, chatId: Uint8Array): Buffer
export declare function deriveWindowKey(srk: Uint8Array, windowIndex: number): Buffer
