/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function generateDek(): Buffer
export declare function generateFileId(): Buffer
export declare function generateSalt(): Buffer
export declare function generateGk(): Buffer
export interface ChunkEnvelope {
  chunkIndex: number
  iv: Buffer
  ciphertext: Buffer
  tag: Buffer
}
export declare function encryptChunk(dek: Uint8Array, fileId: Uint8Array, chunkIndex: number, plaintext: Uint8Array): ChunkEnvelope
export declare function decryptChunk(dek: Uint8Array, fileId: Uint8Array, chunkIndex: number, envelope: ChunkEnvelope): Buffer
export declare function chunkLeafHash(envelope: ChunkEnvelope): Buffer
export declare function merkleRoot(leaves: Array<Uint8Array>): Buffer
export declare function merkleProof(leaves: Array<Uint8Array>, leafIndex: number): Array<Buffer>
export declare function verifyMerkleProof(leaf: Uint8Array, leafIndex: number, totalLeaves: number, proof: Array<Uint8Array>, expectedRoot: Uint8Array): boolean
export interface KdfChoice {
  kind: string
  rounds?: number
  mCost?: number
  tCost?: number
  pCost?: number
  salt?: Buffer
}
export interface WrapEntry {
  kind: string
  salt?: Buffer
  rounds?: number
  mCost?: number
  tCost?: number
  pCost?: number
  recipientId?: Buffer
  gkVersion?: number
  ephemeralX25519?: Buffer
  ciphertextMlKem?: Buffer
  groupId?: Buffer
  wrappedKey: Buffer
}
export declare function wrapDekWithPassword(dek: Uint8Array, password: string, kdf: KdfChoice): WrapEntry
export declare function unwrapDekWithPassword(wrap: WrapEntry, password: string): Buffer
export declare function unwrapDekWithPasswordAsync(wrap: WrapEntry, password: string): Promise<unknown>
export interface KeySubpair {
  x25519: Buffer
  mlKem: Buffer
}
export interface RecipientKeypair {
  publicKey: KeySubpair
  secretKey: KeySubpair
}
export declare function generateRecipientKeypair(): RecipientKeypair
export declare function wrapKeyToRecipient(key: Uint8Array, recipientId: Uint8Array, gkVersion: number, recipientPk: KeySubpair): WrapEntry
export declare function unwrapKeyWithRecipientKey(wrap: WrapEntry, recipientSk: KeySubpair): Buffer
export declare function wrapDekForGroup(dek: Uint8Array, groupId: Uint8Array, gkVersion: number, gk: Uint8Array): WrapEntry
export declare function unwrapDekWithGroupKey(wrap: WrapEntry, gk: Uint8Array): Buffer
export interface Ed25519KeypairObj {
  publicKey: Buffer
  secretKey: Buffer
}
export declare function ed25519KeypairGenerate(): Ed25519KeypairObj
export declare function ed25519Sign(sk: Uint8Array, message: Uint8Array): Buffer
export declare function ed25519Verify(pk: Uint8Array, message: Uint8Array, signature: Uint8Array): boolean
export interface MemberPublicKeyObj {
  recipient: KeySubpair
  signingPk: Buffer
}
export interface SignedMetadata {
  kind: string
  signerPubkey?: Buffer
  timestamp: number
  keyLogId?: Buffer
  sealedGroupId?: Buffer
  sealedGkVersion?: number
  iv?: Buffer
  sealedPayload?: Buffer
  sealedTag?: Buffer
}
export interface HeaderObj {
  version: number
  mode: number
  cipherId: number
  fileId: Buffer
  chunkSize: number
  plaintextSize: number
  merkleRoot: Buffer
  wraps: Array<WrapEntry>
  signedMetadata?: SignedMetadata
  signature?: Buffer
}
export interface ParsedHeaderObj {
  header: HeaderObj
  headerLen: number
}
export interface RewrapResult {
  header: Buffer
  updatedCount: number
}
export declare function rewrapDekInHeader(headerBytes: Uint8Array, oldGk: Uint8Array, newGk: Uint8Array, newGkVersion: number): RewrapResult
export declare function cryptoShredHeader(headerBytes: Uint8Array): Buffer
export declare function signHeaderPlain(header: HeaderObj, signerPk: Uint8Array, signerSk: Uint8Array, keyLogId: Uint8Array, timestamp: number): HeaderObj
export declare function signHeaderSealed(header: HeaderObj, signerPk: Uint8Array, signerSk: Uint8Array, keyLogId: Uint8Array, timestamp: number, sealedGroupId: Uint8Array, sealedGkVersion: number, sealedGk: Uint8Array): HeaderObj
export declare function verifyHeaderSignaturePlain(header: HeaderObj): Buffer
export declare function verifyHeaderSignatureSealed(header: HeaderObj, sealedGk: Uint8Array): Buffer
export interface KeyLogEntry {
  kind: string
  userId?: Buffer
  deviceId: Buffer
  devicePubkey?: Buffer
  humanLabel?: string
  prevHash: Buffer
  timestamp: number
  signature: Buffer
}
export interface SenderInfo {
  signerPubkey: Buffer
  userId: Buffer
  deviceId: Buffer
  deviceWasActive: boolean
  humanLabel?: string
}
export declare function resolveSender(header: HeaderObj, keyLog: KeyLog, sealedGk?: Uint8Array | undefined | null): SenderInfo
export declare class GroupManifest {
  static genesis(groupId: Uint8Array, initialGk: Uint8Array, founderMemberId: Uint8Array, founderRecipientPk: KeySubpair, founderEd25519Pk: Uint8Array, founderEd25519Sk: Uint8Array, timestamp: number): GroupManifest
  static parse(bytes: Uint8Array): GroupManifest
  write(): Buffer
  verify(): void
  addMember(newMemberId: Uint8Array, newMemberPk: MemberPublicKeyObj, currentGk: Uint8Array, adminPk: Uint8Array, adminSk: Uint8Array, timestamp: number): void
  removeMember(removedMemberId: Uint8Array, adminPk: Uint8Array, adminSk: Uint8Array, timestamp: number): void
  rotateGroupKey(newGk: Uint8Array, adminPk: Uint8Array, adminSk: Uint8Array, timestamp: number): number
  shredGroupKey(versionToShred: number, reason: string, adminPk: Uint8Array, adminSk: Uint8Array, timestamp: number): void
  currentMembers(): Array<Buffer>
  currentGkVersion(): number
  findMemberWrap(memberId: Uint8Array): WrapEntry
  findMemberWrapForVersion(memberId: Uint8Array, gkVersion: number): WrapEntry
  isVersionShredded(gkVersion: number): boolean
}
export declare class HeaderClass {
  static parse(bytes: Uint8Array): ParsedHeaderObj
  static write(header: HeaderObj): Buffer
}
export declare class KeyLog {
  static create(authorityPubkey: Uint8Array): KeyLog
  static parse(bytes: Uint8Array): KeyLog
  write(): Buffer
  verify(): void
  registerDevice(userId: Uint8Array, deviceId: Uint8Array, devicePk: Uint8Array, humanLabel: string, authoritySk: Uint8Array, timestamp: number): Buffer
  revokeDevice(deviceId: Uint8Array, authoritySk: Uint8Array, timestamp: number): void
  lookupByEntryHash(hash: Uint8Array): KeyLogEntry | null
  deviceWasActiveAt(deviceId: Uint8Array, timestamp: number): boolean
  userForDevice(deviceId: Uint8Array): Buffer | null
}
