/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'vollcrypt-files-node.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./vollcrypt-files-node.android-arm64.node')
          } else {
            nativeBinding = require('@vollcrypt/files-node-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'vollcrypt-files-node.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./vollcrypt-files-node.android-arm-eabi.node')
          } else {
            nativeBinding = require('@vollcrypt/files-node-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'vollcrypt-files-node.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./vollcrypt-files-node.win32-x64-msvc.node')
          } else {
            nativeBinding = require('@vollcrypt/files-node-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'vollcrypt-files-node.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./vollcrypt-files-node.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('@vollcrypt/files-node-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'vollcrypt-files-node.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./vollcrypt-files-node.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('@vollcrypt/files-node-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'vollcrypt-files-node.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./vollcrypt-files-node.darwin-universal.node')
      } else {
        nativeBinding = require('@vollcrypt/files-node-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'vollcrypt-files-node.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./vollcrypt-files-node.darwin-x64.node')
          } else {
            nativeBinding = require('@vollcrypt/files-node-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'vollcrypt-files-node.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./vollcrypt-files-node.darwin-arm64.node')
          } else {
            nativeBinding = require('@vollcrypt/files-node-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'vollcrypt-files-node.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./vollcrypt-files-node.freebsd-x64.node')
      } else {
        nativeBinding = require('@vollcrypt/files-node-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'vollcrypt-files-node.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./vollcrypt-files-node.linux-x64-musl.node')
            } else {
              nativeBinding = require('@vollcrypt/files-node-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'vollcrypt-files-node.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./vollcrypt-files-node.linux-x64-gnu.node')
            } else {
              nativeBinding = require('@vollcrypt/files-node-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'vollcrypt-files-node.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./vollcrypt-files-node.linux-arm64-musl.node')
            } else {
              nativeBinding = require('@vollcrypt/files-node-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'vollcrypt-files-node.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./vollcrypt-files-node.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('@vollcrypt/files-node-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'vollcrypt-files-node.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./vollcrypt-files-node.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('@vollcrypt/files-node-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'vollcrypt-files-node.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./vollcrypt-files-node.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('@vollcrypt/files-node-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'vollcrypt-files-node.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./vollcrypt-files-node.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('@vollcrypt/files-node-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'vollcrypt-files-node.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./vollcrypt-files-node.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('@vollcrypt/files-node-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'vollcrypt-files-node.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./vollcrypt-files-node.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('@vollcrypt/files-node-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { generateDek, generateFileId, generateSalt, generateGk, encryptChunk, decryptChunk, chunkLeafHash, merkleRoot, merkleProof, verifyMerkleProof, wrapDekWithPassword, unwrapDekWithPassword, unwrapDekWithPasswordAsync, generateRecipientKeypair, wrapKeyToRecipient, unwrapKeyWithRecipientKey, wrapDekForGroup, unwrapDekWithGroupKey, ed25519KeypairGenerate, ed25519Sign, ed25519Verify, hybridKeypairGenerate, hybridSign, hybridVerify, GroupManifest, HeaderClass, rewrapDekInHeader, cryptoShredHeader, signHeaderPlain, signHeaderSealed, verifyHeaderSignaturePlain, verifyHeaderSignatureSealed, KeyLog, resolveSender, sealContainer, isSealed, inspectSealedContainer, verifyContainer, encryptFilePipelinedAsync, decryptFilePipelinedAsync } = nativeBinding

module.exports.generateDek = generateDek
module.exports.generateFileId = generateFileId
module.exports.generateSalt = generateSalt
module.exports.generateGk = generateGk
module.exports.encryptChunk = encryptChunk
module.exports.decryptChunk = decryptChunk
module.exports.chunkLeafHash = chunkLeafHash
module.exports.merkleRoot = merkleRoot
module.exports.merkleProof = merkleProof
module.exports.verifyMerkleProof = verifyMerkleProof
module.exports.wrapDekWithPassword = wrapDekWithPassword
module.exports.unwrapDekWithPassword = unwrapDekWithPassword
module.exports.unwrapDekWithPasswordAsync = unwrapDekWithPasswordAsync
module.exports.generateRecipientKeypair = generateRecipientKeypair
module.exports.wrapKeyToRecipient = wrapKeyToRecipient
module.exports.unwrapKeyWithRecipientKey = unwrapKeyWithRecipientKey
module.exports.wrapDekForGroup = wrapDekForGroup
module.exports.unwrapDekWithGroupKey = unwrapDekWithGroupKey
module.exports.ed25519KeypairGenerate = ed25519KeypairGenerate
module.exports.ed25519Sign = ed25519Sign
module.exports.ed25519Verify = ed25519Verify
module.exports.hybridKeypairGenerate = hybridKeypairGenerate
module.exports.hybridSign = hybridSign
module.exports.hybridVerify = hybridVerify
module.exports.GroupManifest = GroupManifest
module.exports.HeaderClass = HeaderClass
module.exports.rewrapDekInHeader = rewrapDekInHeader
module.exports.cryptoShredHeader = cryptoShredHeader
module.exports.signHeaderPlain = signHeaderPlain
module.exports.signHeaderSealed = signHeaderSealed
module.exports.verifyHeaderSignaturePlain = verifyHeaderSignaturePlain
module.exports.verifyHeaderSignatureSealed = verifyHeaderSignatureSealed
module.exports.KeyLog = KeyLog
module.exports.resolveSender = resolveSender
module.exports.sealContainer = sealContainer
module.exports.isSealed = isSealed
module.exports.inspectSealedContainer = inspectSealedContainer
module.exports.verifyContainer = verifyContainer
module.exports.encryptFilePipelinedAsync = encryptFilePipelinedAsync
module.exports.decryptFilePipelinedAsync = decryptFilePipelinedAsync
