/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface NapiKeyPair {
  publicKey: Buffer
  secretSeed: Buffer
}
export interface NapiIntegrityEntry {
  path: string
  kind: string
  contentDigest: Buffer
  metadataDigest: Buffer
  size: number
}
export interface NapiSnapshotSummary {
  scopeId: string
  root: Buffer
  entryCount: number
  signerKeyId: Buffer
}
export declare function shieldCoreVersion(): string
export declare function generateKeyPair(): NapiKeyPair
export declare function sign(payload: Buffer, secretSeed: Buffer): Buffer
export declare function verify(payload: Buffer, publicKey: Buffer, signature: Buffer): boolean
export declare function createSignedSnapshot(scopeId: string, entries: Array<NapiIntegrityEntry>, createdAtUnixMs: number, secretSeed: Buffer): Buffer
export declare function verifySignedSnapshot(encoded: Buffer): NapiSnapshotSummary
