/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS — manual additions below line 316 */

const { existsSync, readFileSync } = require('fs')
const { open } = require('fs/promises')
const { join } = require('path')
const crypto = require('crypto')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'vollcrypt.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./vollcrypt.android-arm64.node')
          } else {
            nativeBinding = require('@vollcrypt/node-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'vollcrypt.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./vollcrypt.android-arm-eabi.node')
          } else {
            nativeBinding = require('@vollcrypt/node-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'vollcrypt.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./vollcrypt.win32-x64-msvc.node')
          } else {
            nativeBinding = require('@vollcrypt/node-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'vollcrypt.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./vollcrypt.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('@vollcrypt/node-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'vollcrypt.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./vollcrypt.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('@vollcrypt/node-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'vollcrypt.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./vollcrypt.darwin-universal.node')
      } else {
        nativeBinding = require('@vollcrypt/node-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'vollcrypt.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./vollcrypt.darwin-x64.node')
          } else {
            nativeBinding = require('@vollcrypt/node-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'vollcrypt.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./vollcrypt.darwin-arm64.node')
          } else {
            nativeBinding = require('@vollcrypt/node-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'vollcrypt.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./vollcrypt.freebsd-x64.node')
      } else {
        nativeBinding = require('@vollcrypt/node-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'vollcrypt.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./vollcrypt.linux-x64-musl.node')
            } else {
              nativeBinding = require('@vollcrypt/node-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'vollcrypt.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./vollcrypt.linux-x64-gnu.node')
            } else {
              nativeBinding = require('@vollcrypt/node-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'vollcrypt.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./vollcrypt.linux-arm64-musl.node')
            } else {
              nativeBinding = require('@vollcrypt/node-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'vollcrypt.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./vollcrypt.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('@vollcrypt/node-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'vollcrypt.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./vollcrypt.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('@vollcrypt/node-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'vollcrypt.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./vollcrypt.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('@vollcrypt/node-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'vollcrypt.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./vollcrypt.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('@vollcrypt/node-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'vollcrypt.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./vollcrypt.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('@vollcrypt/node-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'vollcrypt.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./vollcrypt.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('@vollcrypt/node-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { generateMnemonic, mnemonicToSeed, generateEd25519Keypair, generateX25519Keypair, ecdhSharedSecret, signMessage, verifySignature, encryptAesGcm, decryptAesGcm, encryptAesGcmPadded, decryptAesGcmPadded, encryptAesGcmChunked, decryptAesGcmChunked, encryptAesGcmChunkedPadded, decryptAesGcmChunkedPadded, derivePbkdf2, deriveHkdf, deriveSrk, deriveWindowKey, wrapKey, unwrapKey, padMessage, packEnvelope, unpackEnvelope, mlKemKeygen, mlKemEncapsulate, mlKemDecapsulate, hybridKemEncapsulate, hybridKemDecapsulate, authenticatedKemEncapsulate, authenticatedKemDecapsulate, registryEmpty, registryAddDevice, registryRevokeDevice, registryGetActiveDevices, generateRatchetKeypair, ratchetSrk, shouldRatchet, transcriptNew, transcriptUpdate, transcriptComputeMessageHash, transcriptVerifySync, sealMessage, unsealMessage, keyLogCreateEntry, keyLogVerifyChain, keyLogCurrentKey, keyLogKeyAtTimestamp, keyLogComputeEntryHash, generateVerificationCode, computeFingerprint, verifyFingerprintsMatch } = nativeBinding

function buildChunkAad(baseAad, chunkIndex) {
  const aadPrefix = baseAad ? Buffer.from(baseAad) : Buffer.alloc(0)
  const indexBuf = Buffer.alloc(4)
  indexBuf.writeUInt32BE(chunkIndex, 0)
  return Buffer.concat([aadPrefix, indexBuf])
}

async function encryptFileChunked(inputPath, outputPath, key, aad, chunkSize) {
  if (!chunkSize || chunkSize <= 0) {
    throw new Error('Invalid chunk size, must be greater than 0')
  }
  const inputHandle = await open(inputPath, 'r')
  const outputHandle = await open(outputPath, 'w')
  try {
    const stat = await inputHandle.stat()
    const totalLen = stat.size
    const chunkCount = totalLen === 0 ? 1 : Math.ceil(totalLen / chunkSize)
    if (chunkCount > 0xffffffff) {
      throw new Error('Chunk count exceeds supported maximum')
    }
    const header = Buffer.alloc(4)
    header.writeUInt32BE(chunkCount, 0)
    await outputHandle.write(header, 0, 4, 0)
    let outPos = 4
    let offset = 0
    let index = 0
    while (index < chunkCount) {
      const remaining = Math.max(0, totalLen - offset)
      const readSize = totalLen === 0 ? 0 : Math.min(chunkSize, remaining)
      const chunk = Buffer.alloc(readSize)
      if (readSize > 0) {
        const { bytesRead } = await inputHandle.read(chunk, 0, readSize, offset)
        if (bytesRead !== readSize) {
          throw new Error('Unexpected EOF while reading input')
        }
      }
      const aadChunk = buildChunkAad(aad, index)
      const encrypted = encryptAesGcm(key, chunk, aadChunk)
      const chunkHeader = Buffer.alloc(8)
      chunkHeader.writeUInt32BE(index, 0)
      chunkHeader.writeUInt32BE(encrypted.length, 4)
      await outputHandle.write(chunkHeader, 0, 8, outPos)
      outPos += 8
      await outputHandle.write(encrypted, 0, encrypted.length, outPos)
      outPos += encrypted.length
      offset += readSize
      index += 1
      if (totalLen === 0) {
        break
      }
    }
  } finally {
    await inputHandle.close()
    await outputHandle.close()
  }
}

async function decryptFileChunked(inputPath, outputPath, key, aad) {
  const inputHandle = await open(inputPath, 'r')
  const outputHandle = await open(outputPath, 'w')
  try {
    const stat = await inputHandle.stat()
    if (stat.size < 4) {
      throw new Error('Encrypted data too short')
    }
    const countBuf = Buffer.alloc(4)
    const countRead = await inputHandle.read(countBuf, 0, 4, 0)
    if (countRead.bytesRead !== 4) {
      throw new Error('Encrypted data too short')
    }
    const chunkCount = countBuf.readUInt32BE(0)
    if (chunkCount === 0) {
      throw new Error('Invalid chunk count')
    }
    let inPos = 4
    for (let expected = 0; expected < chunkCount; expected += 1) {
      const header = Buffer.alloc(8)
      const headerRead = await inputHandle.read(header, 0, 8, inPos)
      if (headerRead.bytesRead !== 8) {
        throw new Error('Encrypted data truncated')
      }
      const chunkIndex = header.readUInt32BE(0)
      const chunkLen = header.readUInt32BE(4)
      if (chunkIndex !== expected) {
        throw new Error('Chunk index mismatch')
      }
      if (chunkLen === 0) {
        throw new Error('Invalid chunk length')
      }
      inPos += 8
      const encrypted = Buffer.alloc(chunkLen)
      const chunkRead = await inputHandle.read(encrypted, 0, chunkLen, inPos)
      if (chunkRead.bytesRead !== chunkLen) {
        throw new Error('Encrypted data truncated')
      }
      const aadChunk = buildChunkAad(aad, chunkIndex)
      const decrypted = decryptAesGcm(key, encrypted, aadChunk)
      await outputHandle.write(decrypted, 0, decrypted.length, null)
      inPos += chunkLen
    }
    if (inPos !== stat.size) {
      throw new Error('Trailing data after chunks')
    }
  } finally {
    await inputHandle.close()
    await outputHandle.close()
  }
}

const DEFAULT_LICENSE_SERVER = 'https://api.vollcrypt.com'
let licenseTracker = null
let licenseInitPromise = null

function resolveLicenseConfig(config = {}) {
  const envKey = process.env.VOLLCRYPT_LICENSE_KEY
  const envServer = process.env.VOLLCRYPT_LICENSE_SERVER
  const envInterval = process.env.VOLLCRYPT_LICENSE_REPORT_INTERVAL_MS
  const envOffline = process.env.VOLLCRYPT_LICENSE_OFFLINE_FALLBACK
  const reportIntervalMs = config.reportIntervalMs ?? (envInterval ? Number(envInterval) : 3_600_000)
  const offlineFallback = config.offlineFallback ?? (envOffline ? envOffline !== 'false' : true)
  return {
    licenseKey: config.licenseKey ?? envKey ?? null,
    serverUrl: config.serverUrl ?? envServer ?? DEFAULT_LICENSE_SERVER,
    reportIntervalMs,
    offlineFallback,
  }
}

class LicenseTracker {
  constructor(config = {}) {
    this.config = resolveLicenseConfig(config)
    this.trackedUsers = new Set()
    this.status = null
    this.reportTimer = null
  }

  async initialize() {
    try {
      const status = await this.validateLicense()
      this.status = status
      this.startReportingCycle()
      return status
    } catch (error) {
      if (this.config.offlineFallback) {
        // console.warn('[Vollcrypt] License server unreachable. Offline mode active.')
        this.status = {
          valid: true,
          tier: 'free',
          monthlyActiveUsers: 0,
          limit: 500,
          limitReached: false,
        }
        return this.status
      }
      throw error
    }
  }

  trackUser(userId) {
    const hashed = crypto
      .createHash('sha256')
      .update(`vollcrypt:${userId}`)
      .digest('hex')
    this.trackedUsers.add(hashed)
    if (this.status && this.status.limit > 0) {
      if (this.trackedUsers.size > this.status.limit) {
        this.handleLimitExceeded()
      }
    }
  }

  getMonthlyActiveUsers() {
    return this.trackedUsers.size
  }

  getStatus() {
    return this.status
  }

  destroy() {
    if (this.reportTimer) {
      clearInterval(this.reportTimer)
      this.reportTimer = null
    }
  }

  async validateLicense() {
    if (typeof fetch !== 'function') {
      throw new Error('fetch is not available in this runtime')
    }
    const response = await fetch(`${this.config.serverUrl}/v1/license/validate`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        licenseKey: this.config.licenseKey ?? null,
        sdkVersion: '0.1.0',
      }),
    })
    if (!response.ok) {
      throw new Error(`License validation failed: ${response.status}`)
    }
    return response.json()
  }

  async reportUsage() {
    if (!this.config.licenseKey) return
    try {
      await fetch(`${this.config.serverUrl}/v1/license/report`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          licenseKey: this.config.licenseKey,
          monthlyActiveUsers: this.trackedUsers.size,
          reportedAt: Date.now(),
        }),
      })
    } catch {}
  }

  startReportingCycle() {
    this.reportTimer = setInterval(
      () => this.reportUsage(),
      this.config.reportIntervalMs
    )
  }

  handleLimitExceeded() {
    const tier = this.status?.tier ?? 'free'
    const limit = this.status?.limit ?? 500
    // console.warn(
    //   `[Vollcrypt] Monthly active user limit reached (${limit} MAU, tier: ${tier}). ` +
    //   `Library will continue to function. ` +
    //   `Upgrade your plan at: https://github.com/BeratVural/vollcrypt`
    // )
  }
}

async function initializeLicense(config = {}) {
  const resolved = resolveLicenseConfig(config)
  if (!licenseTracker) {
    licenseTracker = new LicenseTracker(resolved)
  }
  if (!licenseInitPromise) {
    licenseInitPromise = licenseTracker.initialize()
  }
  return licenseInitPromise
}

function getLicenseStatus() {
  return licenseTracker ? licenseTracker.getStatus() : null
}

function trackLicensedUser(userId) {
  if (!licenseTracker) {
    licenseTracker = new LicenseTracker({})
    if (!licenseInitPromise) {
      licenseInitPromise = licenseTracker.initialize().catch(() => null)
    }
  }
  licenseTracker.trackUser(userId)
}

function destroyLicenseTracker() {
  if (licenseTracker) {
    licenseTracker.destroy()
  }
  licenseTracker = null
  licenseInitPromise = null
}

const envKey = process.env.VOLLCRYPT_LICENSE_KEY
const envServer = process.env.VOLLCRYPT_LICENSE_SERVER
if (envKey || envServer) {
  initializeLicense({ licenseKey: envKey ?? undefined, serverUrl: envServer ?? undefined }).catch(() => null)
}

module.exports.generateMnemonic = generateMnemonic
module.exports.mnemonicToSeed = mnemonicToSeed
module.exports.generateEd25519Keypair = generateEd25519Keypair
module.exports.generateX25519Keypair = generateX25519Keypair
module.exports.ecdhSharedSecret = ecdhSharedSecret
module.exports.signMessage = signMessage
module.exports.verifySignature = verifySignature
module.exports.encryptAesGcm = encryptAesGcm
module.exports.decryptAesGcm = decryptAesGcm
module.exports.encryptAesGcmPadded = encryptAesGcmPadded
module.exports.decryptAesGcmPadded = decryptAesGcmPadded
module.exports.encryptAesGcmChunked = encryptAesGcmChunked
module.exports.decryptAesGcmChunked = decryptAesGcmChunked
module.exports.encryptAesGcmChunkedPadded = encryptAesGcmChunkedPadded
module.exports.decryptAesGcmChunkedPadded = decryptAesGcmChunkedPadded
module.exports.encryptFileChunked = encryptFileChunked
module.exports.decryptFileChunked = decryptFileChunked
module.exports.derivePbkdf2 = derivePbkdf2
module.exports.deriveHkdf = deriveHkdf
module.exports.deriveSrk = deriveSrk
module.exports.deriveWindowKey = deriveWindowKey
module.exports.wrapKey = wrapKey
module.exports.unwrapKey = unwrapKey
module.exports.padMessage = padMessage
module.exports.packEnvelope = packEnvelope
module.exports.unpackEnvelope = unpackEnvelope
module.exports.mlKemKeygen = mlKemKeygen
module.exports.mlKemEncapsulate = mlKemEncapsulate
module.exports.mlKemDecapsulate = mlKemDecapsulate
module.exports.hybridKemEncapsulate = hybridKemEncapsulate
module.exports.hybridKemDecapsulate = hybridKemDecapsulate
module.exports.authenticatedKemEncapsulate = authenticatedKemEncapsulate
module.exports.authenticatedKemDecapsulate = authenticatedKemDecapsulate
module.exports.registryEmpty = registryEmpty
module.exports.registryAddDevice = registryAddDevice
module.exports.registryRevokeDevice = registryRevokeDevice
module.exports.registryGetActiveDevices = registryGetActiveDevices
module.exports.generateRatchetKeypair = generateRatchetKeypair
module.exports.ratchetSrk = ratchetSrk
module.exports.shouldRatchet = shouldRatchet
module.exports.transcriptNew = transcriptNew
module.exports.transcriptUpdate = transcriptUpdate
module.exports.transcriptComputeMessageHash = transcriptComputeMessageHash
module.exports.transcriptVerifySync = transcriptVerifySync
module.exports.sealMessage = sealMessage
module.exports.unsealMessage = unsealMessage
module.exports.keyLogCreateEntry = keyLogCreateEntry
module.exports.keyLogVerifyChain = keyLogVerifyChain
module.exports.keyLogCurrentKey = keyLogCurrentKey
module.exports.keyLogKeyAtTimestamp = keyLogKeyAtTimestamp
module.exports.keyLogComputeEntryHash = keyLogComputeEntryHash
module.exports.generateVerificationCode = generateVerificationCode
module.exports.computeFingerprint = computeFingerprint
module.exports.verifyFingerprintsMatch = verifyFingerprintsMatch
module.exports.initializeLicense = initializeLicense
module.exports.getLicenseStatus = getLicenseStatus
module.exports.trackLicensedUser = trackLicensedUser
module.exports.destroyLicenseTracker = destroyLicenseTracker
